clone:
  tags: true
build:
  image: grase/build-images:trusty
  commands:
    - dpkg-buildpackage


publish:
  sftp:
    host: $$SFTP_HOST
    username: artifacts
    password: $$SFTP_PASSWORD
    files:
      - './build-area/*.deb'
      - './build-area/*.build'
      - './build-area/*.changes'
      - './build-area/*.dsc'
      - './build-area/*.tar.xz'
    destination_path: /home/artifacts/coova-chilli/
