.build_template: &build_definition
  stage: build
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../coova-chilli_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

jessie-amd64:
  <<: *build_definition
  image: grase/build-images:jessie

trusty-amd64:
  <<: *build_definition
  image: grase/build-images:trusty

xenial-amd64:
  <<: *build_definition
  image: grase/build-images:xenial

jessie-i386:
  <<: *build_definition
  image: grase/build-images:jessie
  script:
    - dpkg-buildpackage -ai386 -d
    - mkdir artifacts
    - mv -v ../coova-chilli_* artifacts/

jessie-armhf:
  <<: *build_definition
  image: grase/build-images:jessie
  script:
    - dpkg-buildpackage -aarmhf -d
    - mkdir artifacts
    - mv -v ../coova-chilli_* artifacts/

jessie-armel:
  <<: *build_definition
  image: grase/build-images:jessie
  script:
    - dpkg-buildpackage -aarmel -d
    - mkdir artifacts
    - mv -v ../coova-chilli_* artifacts/
