.build_template: &build_definition
  stage: build
  script:
    - dch -v $(git describe --tags |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage -a$BUILD_ARCH -d
    - mkdir artifacts
    - mv -v ../coova-chilli_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

variables:
  BUILD_ARCH: amd64

jessie-amd64:
  <<: *build_definition
  image: grase/build-images:jessie

trusty-amd64:
  <<: *build_definition
  image: grase/build-images:trusty

xenial-amd64:
  <<: *build_definition
  image: grase/build-images:xenial

xenial-i386:
  <<: *build_definition
  image: grase/build-images:xenial
  variables:
    BUILD_ARCH: i386

xenial-armhf:
  <<: *build_definition
  image: grase/build-images:xenial
  variables:
    BUILD_ARCH: armhf

jessie-i386:
  <<: *build_definition
  image: grase/build-images:jessie
  variables:
    BUILD_ARCH: i386

jessie-armhf:
  <<: *build_definition
  image: grase/build-images:jessie
  variables:
    BUILD_ARCH: armhf

jessie-armel:
  <<: *build_definition
  image: grase/build-images:jessie
  variables:
    BUILD_ARCH: armel
