
jessie-amd64:
  image: grase/build-images:jessie
  script:
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../coova-chilli* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-amd64:
  image: grase/build-images:trusty
  script:
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../coova-chilli* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week


jessie-i386:
  image: dovetailautomata/docker-cross-builder
  script:
    - DPKG_ROOT=$I386_ROOT LDFLAGS="-m32 --sysroot=$I386_ROOT" CPPFLAGS="-m32 --sysroot=$I386_ROOT" dpkg-buildpackage -uc -us -a i386 -B -d
    - mkdir artifacts
    - mv -v ../coova-chilli* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

jessie-armhf:
  image: dovetailautomata/docker-cross-builder
  script:
    - DPKG_ROOT=$ARM_ROOT LDFLAGS=--sysroot=$ARM_ROOT CPPFLAGS=--sysroot=$ARM_ROOT dpkg-buildpackage -uc -us -a armhf -B -d
    - mkdir artifacts
    - mv -v ../coova-chilli* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

jessie-raspbian:
  image: dovetailautomata/docker-cross-builder
  script:
    - DPKG_ROOT=$RPI_ROOT LDFLAGS=--sysroot=$RPI_ROOT CPPFLAGS=--sysroot=$RPI_ROOT dpkg-buildpackage -uc -us -a armhf -B -d
    - mkdir artifacts
    - mv -v ../coova-chilli* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
